#!/usr/bin/env python3
"""Generate behavioral tests for L5 static site generator.

Produces test_ssg.py from the behavioral specification in SPEC.md.
Tests verify observable behavior without reference to any existing implementation.
"""
import os
import sys


def main():
    output_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "test_ssg.py")
    with open(output_path, "w") as f:
        f.write(TEST_CONTENT)
    count = TEST_CONTENT.count("    def test_")
    print(f"Generated {output_path}")
    print(f"Total test methods: {count}")


TEST_CONTENT = r'''#!/usr/bin/env python3
"""Behavioral tests for L5 static site generator.

Generated by generate_tests.py from SPEC.md behavioral description.
Tests verify observable behavior using temporary directories.
No network access required. No running server required for core tests.
"""

import os
import shutil
import subprocess
import sys
import tempfile
import textwrap
import unittest


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def create_project(base, config_yaml=None, content_files=None, template_files=None):
    """Create a minimal SSG project in base directory.

    Args:
        base: Root directory for the project.
        config_yaml: YAML string for site.yaml. None = no config file.
        content_files: Dict of {relative_path: content_string}.
        template_files: Dict of {relative_path: template_string}.
    """
    if config_yaml is not None:
        with open(os.path.join(base, "site.yaml"), "w") as f:
            f.write(config_yaml)

    content_dir = os.path.join(base, "content")
    os.makedirs(content_dir, exist_ok=True)
    if content_files:
        for rel_path, content in content_files.items():
            full = os.path.join(content_dir, rel_path)
            os.makedirs(os.path.dirname(full), exist_ok=True)
            with open(full, "w") as f:
                f.write(textwrap.dedent(content))

    tmpl_dir = os.path.join(base, "templates")
    os.makedirs(tmpl_dir, exist_ok=True)
    if template_files:
        for rel_path, content in template_files.items():
            full = os.path.join(tmpl_dir, rel_path)
            os.makedirs(os.path.dirname(full), exist_ok=True)
            with open(full, "w") as f:
                f.write(textwrap.dedent(content))


BASE_TEMPLATE = """\
<!DOCTYPE html>
<html>
<head><title>{{ page.title }} - {{ site.title }}</title></head>
<body>
<nav>{% for item in nav %}<a href="{{ item.url }}">{{ item.title }}</a> {% endfor %}</nav>
<main>{% block content %}{% endblock %}</main>
</body>
</html>
"""

PAGE_TEMPLATE = """\
{% extends "base.html" %}
{% block content %}
<h1>{{ page.title }}</h1>
{{ page.content }}
{% endblock %}
"""

MINIMAL_TEMPLATES = {
    "base.html": BASE_TEMPLATE,
    "page.html": PAGE_TEMPLATE,
}

MINIMAL_CONFIG = """\
title: Test Site
base_url: /
"""


def run_ssg(args, cwd, env=None):
    """Run the SSG CLI and return (returncode, stdout, stderr)."""
    cmd = [sys.executable, "-m", "ssg"] + args
    run_env = os.environ.copy()
    if env:
        run_env.update(env)
    result = subprocess.run(
        cmd, capture_output=True, text=True, cwd=cwd, env=run_env
    )
    return result.returncode, result.stdout, result.stderr


# ---------------------------------------------------------------------------
# Config tests
# ---------------------------------------------------------------------------

class TestConfig(unittest.TestCase):
    """Tests for configuration loading."""

    def setUp(self):
        self.tmpdir = tempfile.mkdtemp(prefix="ssg_test_")

    def tearDown(self):
        shutil.rmtree(self.tmpdir, ignore_errors=True)

    def test_default_config_when_no_file(self):
        """Config loader returns defaults when site.yaml is missing."""
        create_project(self.tmpdir, config_yaml=None,
                       content_files={"index.md": "# Hello\n"},
                       template_files=MINIMAL_TEMPLATES)
        rc, out, err = run_ssg(["build"], self.tmpdir)
        self.assertEqual(rc, 0, f"Build failed:\n{err}")
        # Default output dir is 'output'
        self.assertTrue(os.path.isdir(os.path.join(self.tmpdir, "output")))

    def test_custom_config_values(self):
        """Config values from site.yaml override defaults."""
        config = "title: Custom Title\noutput_dir: _site\n"
        create_project(self.tmpdir, config_yaml=config,
                       content_files={"index.md": "---\ntitle: Home\n---\n# Home\n"},
                       template_files=MINIMAL_TEMPLATES)
        rc, out, err = run_ssg(["build"], self.tmpdir)
        self.assertEqual(rc, 0, f"Build failed:\n{err}")
        # Custom output dir
        self.assertTrue(os.path.isdir(os.path.join(self.tmpdir, "_site")))
        # Site title in rendered output
        index_html = os.path.join(self.tmpdir, "_site", "index.html")
        self.assertTrue(os.path.isfile(index_html))
        with open(index_html) as f:
            html = f.read()
        self.assertIn("Custom Title", html)

    def test_malformed_yaml_config(self):
        """Malformed YAML in config file produces clear error and exit 1."""
        with open(os.path.join(self.tmpdir, "site.yaml"), "w") as f:
            f.write("title: [unterminated\n")
        os.makedirs(os.path.join(self.tmpdir, "content"), exist_ok=True)
        os.makedirs(os.path.join(self.tmpdir, "templates"), exist_ok=True)
        rc, out, err = run_ssg(["build"], self.tmpdir)
        self.assertNotEqual(rc, 0)
        # Should mention config error, not show Python traceback
        combined = out + err
        self.assertNotIn("Traceback", combined)


# ---------------------------------------------------------------------------
# Front matter tests
# ---------------------------------------------------------------------------

class TestFrontMatter(unittest.TestCase):
    """Tests for YAML front matter parsing."""

    def setUp(self):
        self.tmpdir = tempfile.mkdtemp(prefix="ssg_test_")

    def tearDown(self):
        shutil.rmtree(self.tmpdir, ignore_errors=True)

    def test_page_with_front_matter(self):
        """Page with front matter has correct title in output."""
        create_project(self.tmpdir, config_yaml=MINIMAL_CONFIG,
                       content_files={
                           "about.md": "---\ntitle: About Us\n---\nWelcome to about.\n"
                       },
                       template_files=MINIMAL_TEMPLATES)
        rc, _, err = run_ssg(["build"], self.tmpdir)
        self.assertEqual(rc, 0, f"Build failed:\n{err}")
        html_path = os.path.join(self.tmpdir, "output", "about", "index.html")
        self.assertTrue(os.path.isfile(html_path), f"Missing: {html_path}")
        with open(html_path) as f:
            html = f.read()
        self.assertIn("About Us", html)

    def test_page_without_front_matter(self):
        """Page without front matter still builds with derived title."""
        create_project(self.tmpdir, config_yaml=MINIMAL_CONFIG,
                       content_files={
                           "hello-world.md": "# Just Content\n\nNo front matter here.\n"
                       },
                       template_files=MINIMAL_TEMPLATES)
        rc, _, err = run_ssg(["build"], self.tmpdir)
        self.assertEqual(rc, 0, f"Build failed:\n{err}")
        html_path = os.path.join(self.tmpdir, "output", "hello-world", "index.html")
        self.assertTrue(os.path.isfile(html_path))

    def test_draft_pages_excluded(self):
        """Pages with draft: true are not written to output."""
        create_project(self.tmpdir, config_yaml=MINIMAL_CONFIG,
                       content_files={
                           "published.md": "---\ntitle: Published\n---\nVisible.\n",
                           "secret.md": "---\ntitle: Secret\ndraft: true\n---\nHidden.\n",
                       },
                       template_files=MINIMAL_TEMPLATES)
        rc, _, err = run_ssg(["build"], self.tmpdir)
        self.assertEqual(rc, 0, f"Build failed:\n{err}")
        self.assertTrue(os.path.exists(
            os.path.join(self.tmpdir, "output", "published", "index.html")))
        self.assertFalse(os.path.exists(
            os.path.join(self.tmpdir, "output", "secret")))

    def test_custom_template_in_front_matter(self):
        """Per-page template override via front matter."""
        custom_tmpl = "<article>{{ page.title }}: {{ page.content }}</article>"
        templates = dict(MINIMAL_TEMPLATES)
        templates["custom.html"] = custom_tmpl
        create_project(self.tmpdir, config_yaml=MINIMAL_CONFIG,
                       content_files={
                           "special.md": "---\ntitle: Special\ntemplate: custom.html\n---\nCustom page.\n"
                       },
                       template_files=templates)
        rc, _, err = run_ssg(["build"], self.tmpdir)
        self.assertEqual(rc, 0, f"Build failed:\n{err}")
        html_path = os.path.join(self.tmpdir, "output", "special", "index.html")
        with open(html_path) as f:
            html = f.read()
        self.assertIn("<article>", html)
        self.assertIn("Special", html)

    def test_extra_front_matter_keys_available(self):
        """Extra front matter keys are available as template variables."""
        tmpl = "{{ page.title }} by {{ page.author }}"
        templates = dict(MINIMAL_TEMPLATES)
        templates["byline.html"] = tmpl
        create_project(self.tmpdir, config_yaml=MINIMAL_CONFIG,
                       content_files={
                           "post.md": "---\ntitle: Post\nauthor: Alice\ntemplate: byline.html\n---\nBody.\n"
                       },
                       template_files=templates)
        rc, _, err = run_ssg(["build"], self.tmpdir)
        self.assertEqual(rc, 0, f"Build failed:\n{err}")
        html_path = os.path.join(self.tmpdir, "output", "post", "index.html")
        with open(html_path) as f:
            html = f.read()
        self.assertIn("Alice", html)


# ---------------------------------------------------------------------------
# Content loading and slug generation
# ---------------------------------------------------------------------------

class TestContentLoading(unittest.TestCase):
    """Tests for content directory walking and slug generation."""

    def setUp(self):
        self.tmpdir = tempfile.mkdtemp(prefix="ssg_test_")

    def tearDown(self):
        shutil.rmtree(self.tmpdir, ignore_errors=True)

    def test_nested_directory_structure(self):
        """Nested content directories produce correct output paths."""
        create_project(self.tmpdir, config_yaml=MINIMAL_CONFIG,
                       content_files={
                           "index.md": "---\ntitle: Home\n---\n# Home\n",
                           "blog/first.md": "---\ntitle: First Post\n---\n# First\n",
                           "blog/second.md": "---\ntitle: Second Post\n---\n# Second\n",
                           "docs/guide.md": "---\ntitle: Guide\n---\n# Guide\n",
                       },
                       template_files=MINIMAL_TEMPLATES)
        rc, _, err = run_ssg(["build"], self.tmpdir)
        self.assertEqual(rc, 0, f"Build failed:\n{err}")
        output = self.tmpdir + "/output"
        self.assertTrue(os.path.isfile(f"{output}/index.html"))
        self.assertTrue(os.path.isfile(f"{output}/blog/first/index.html"))
        self.assertTrue(os.path.isfile(f"{output}/blog/second/index.html"))
        self.assertTrue(os.path.isfile(f"{output}/docs/guide/index.html"))

    def test_index_md_gets_directory_slug(self):
        """index.md in a subdirectory maps to the directory slug."""
        create_project(self.tmpdir, config_yaml=MINIMAL_CONFIG,
                       content_files={
                           "blog/index.md": "---\ntitle: Blog\n---\n# Blog Index\n",
                       },
                       template_files=MINIMAL_TEMPLATES)
        rc, _, err = run_ssg(["build"], self.tmpdir)
        self.assertEqual(rc, 0, f"Build failed:\n{err}")
        # blog/index.md -> output/blog/index.html (not output/blog/index/index.html)
        self.assertTrue(os.path.isfile(
            os.path.join(self.tmpdir, "output", "blog", "index.html")))
        self.assertFalse(os.path.isdir(
            os.path.join(self.tmpdir, "output", "blog", "index")))

    def test_non_markdown_files_ignored(self):
        """Non-.md files in content directory are not processed."""
        content_dir = os.path.join(self.tmpdir, "content")
        create_project(self.tmpdir, config_yaml=MINIMAL_CONFIG,
                       content_files={"page.md": "---\ntitle: Page\n---\nContent.\n"},
                       template_files=MINIMAL_TEMPLATES)
        # Add a non-md file
        with open(os.path.join(content_dir, "image.png"), "wb") as f:
            f.write(b"\x89PNG")
        with open(os.path.join(content_dir, "notes.txt"), "w") as f:
            f.write("plain text")
        rc, _, err = run_ssg(["build"], self.tmpdir)
        self.assertEqual(rc, 0, f"Build failed:\n{err}")
        # Only the .md file produces output
        output = self.tmpdir + "/output"
        self.assertTrue(os.path.isfile(f"{output}/page/index.html"))
        self.assertFalse(os.path.exists(f"{output}/image.png"))
        self.assertFalse(os.path.exists(f"{output}/notes.txt"))

    def test_empty_content_directory(self):
        """Build succeeds with empty content directory (zero pages)."""
        create_project(self.tmpdir, config_yaml=MINIMAL_CONFIG,
                       content_files={},
                       template_files=MINIMAL_TEMPLATES)
        rc, _, err = run_ssg(["build"], self.tmpdir)
        self.assertEqual(rc, 0, f"Build should succeed with empty content:\n{err}")

    def test_title_derived_from_filename(self):
        """When front matter has no title, derive from filename."""
        create_project(self.tmpdir, config_yaml=MINIMAL_CONFIG,
                       content_files={
                           "my-cool-page.md": "Just content, no front matter.\n"
                       },
                       template_files=MINIMAL_TEMPLATES)
        rc, _, err = run_ssg(["build"], self.tmpdir)
        self.assertEqual(rc, 0, f"Build failed:\n{err}")
        html_path = os.path.join(self.tmpdir, "output", "my-cool-page", "index.html")
        with open(html_path) as f:
            html = f.read()
        # Title should be derived: "my-cool-page" -> "My Cool Page"
        self.assertIn("My Cool Page", html)


# ---------------------------------------------------------------------------
# Navigation
# ---------------------------------------------------------------------------

class TestNavigation(unittest.TestCase):
    """Tests for navigation tree generation."""

    def setUp(self):
        self.tmpdir = tempfile.mkdtemp(prefix="ssg_test_")

    def tearDown(self):
        shutil.rmtree(self.tmpdir, ignore_errors=True)

    def test_nav_contains_all_pages(self):
        """Navigation includes links to all non-draft pages."""
        create_project(self.tmpdir, config_yaml=MINIMAL_CONFIG,
                       content_files={
                           "index.md": "---\ntitle: Home\n---\n# Home\n",
                           "about.md": "---\ntitle: About\n---\n# About\n",
                           "contact.md": "---\ntitle: Contact\n---\n# Contact\n",
                       },
                       template_files=MINIMAL_TEMPLATES)
        rc, _, err = run_ssg(["build"], self.tmpdir)
        self.assertEqual(rc, 0, f"Build failed:\n{err}")
        with open(os.path.join(self.tmpdir, "output", "index.html")) as f:
            html = f.read()
        # All three pages should appear in nav
        self.assertIn("Home", html)
        self.assertIn("About", html)
        self.assertIn("Contact", html)

    def test_nav_excludes_drafts(self):
        """Draft pages do not appear in navigation."""
        create_project(self.tmpdir, config_yaml=MINIMAL_CONFIG,
                       content_files={
                           "index.md": "---\ntitle: Home\n---\n# Home\n",
                           "visible.md": "---\ntitle: Visible\n---\nYes.\n",
                           "hidden.md": "---\ntitle: Hidden\ndraft: true\n---\nNo.\n",
                       },
                       template_files=MINIMAL_TEMPLATES)
        rc, _, err = run_ssg(["build"], self.tmpdir)
        self.assertEqual(rc, 0, f"Build failed:\n{err}")
        with open(os.path.join(self.tmpdir, "output", "index.html")) as f:
            html = f.read()
        self.assertIn("Visible", html)
        self.assertNotIn("Hidden", html)

    def test_nav_links_are_valid(self):
        """Navigation links point to correct output paths."""
        create_project(self.tmpdir, config_yaml=MINIMAL_CONFIG,
                       content_files={
                           "index.md": "---\ntitle: Home\n---\n# Home\n",
                           "about.md": "---\ntitle: About\n---\n# About\n",
                       },
                       template_files=MINIMAL_TEMPLATES)
        rc, _, err = run_ssg(["build"], self.tmpdir)
        self.assertEqual(rc, 0, f"Build failed:\n{err}")
        with open(os.path.join(self.tmpdir, "output", "index.html")) as f:
            html = f.read()
        # Nav should contain a link to /about/ or about/
        self.assertRegex(html, r'href="[/]?about[/]?"')


# ---------------------------------------------------------------------------
# Rendering
# ---------------------------------------------------------------------------

class TestRendering(unittest.TestCase):
    """Tests for Markdown rendering and template application."""

    def setUp(self):
        self.tmpdir = tempfile.mkdtemp(prefix="ssg_test_")

    def tearDown(self):
        shutil.rmtree(self.tmpdir, ignore_errors=True)

    def test_markdown_rendered_to_html(self):
        """Markdown content is converted to HTML in output."""
        create_project(self.tmpdir, config_yaml=MINIMAL_CONFIG,
                       content_files={
                           "test.md": "---\ntitle: Test\n---\n# Heading\n\nA paragraph with **bold** text.\n"
                       },
                       template_files=MINIMAL_TEMPLATES)
        rc, _, err = run_ssg(["build"], self.tmpdir)
        self.assertEqual(rc, 0, f"Build failed:\n{err}")
        with open(os.path.join(self.tmpdir, "output", "test", "index.html")) as f:
            html = f.read()
        self.assertIn("<h1>Heading</h1>", html)
        self.assertIn("<strong>bold</strong>", html)

    def test_template_inheritance(self):
        """Page template extends base template correctly."""
        create_project(self.tmpdir, config_yaml=MINIMAL_CONFIG,
                       content_files={
                           "page.md": "---\ntitle: My Page\n---\nBody text.\n"
                       },
                       template_files=MINIMAL_TEMPLATES)
        rc, _, err = run_ssg(["build"], self.tmpdir)
        self.assertEqual(rc, 0, f"Build failed:\n{err}")
        with open(os.path.join(self.tmpdir, "output", "page", "index.html")) as f:
            html = f.read()
        # From base.html
        self.assertIn("<!DOCTYPE html>", html)
        self.assertIn("<nav>", html)
        # From page.html block
        self.assertIn("Body text.", html)
        # Title from base template
        self.assertIn("My Page - Test Site", html)

    def test_syntax_highlighting_in_code_blocks(self):
        """Fenced code blocks with language get syntax highlighting markup."""
        md_content = '---\ntitle: Code\n---\n\n```python\ndef hello():\n    print("world")\n```\n'
        create_project(self.tmpdir, config_yaml=MINIMAL_CONFIG,
                       content_files={"code.md": md_content},
                       template_files=MINIMAL_TEMPLATES)
        rc, _, err = run_ssg(["build"], self.tmpdir)
        self.assertEqual(rc, 0, f"Build failed:\n{err}")
        with open(os.path.join(self.tmpdir, "output", "code", "index.html")) as f:
            html = f.read()
        # Pygments should produce some kind of highlighting markup
        # (either class-based <span class="..."> or inline style)
        self.assertRegex(html, r'class="[^"]*highlight[^"]*"',
                         "Expected Pygments highlight class in code block output")

    def test_site_title_in_template(self):
        """site.title from config is available in templates."""
        config = "title: My Awesome Site\n"
        create_project(self.tmpdir, config_yaml=config,
                       content_files={
                           "index.md": "---\ntitle: Home\n---\nWelcome.\n"
                       },
                       template_files=MINIMAL_TEMPLATES)
        rc, _, err = run_ssg(["build"], self.tmpdir)
        self.assertEqual(rc, 0, f"Build failed:\n{err}")
        with open(os.path.join(self.tmpdir, "output", "index.html")) as f:
            html = f.read()
        self.assertIn("My Awesome Site", html)

    def test_missing_template_produces_error(self):
        """Referencing a non-existent template produces a clear error."""
        create_project(self.tmpdir, config_yaml=MINIMAL_CONFIG,
                       content_files={
                           "broken.md": "---\ntitle: Broken\ntemplate: nonexistent.html\n---\nOops.\n"
                       },
                       template_files=MINIMAL_TEMPLATES)
        rc, out, err = run_ssg(["build"], self.tmpdir)
        self.assertNotEqual(rc, 0)
        combined = out + err
        self.assertNotIn("Traceback", combined)


# ---------------------------------------------------------------------------
# Build pipeline
# ---------------------------------------------------------------------------

class TestBuildPipeline(unittest.TestCase):
    """Tests for the end-to-end build pipeline."""

    def setUp(self):
        self.tmpdir = tempfile.mkdtemp(prefix="ssg_test_")

    def tearDown(self):
        shutil.rmtree(self.tmpdir, ignore_errors=True)

    def test_full_build_end_to_end(self):
        """Complete build from content to output."""
        create_project(self.tmpdir, config_yaml=MINIMAL_CONFIG,
                       content_files={
                           "index.md": "---\ntitle: Home\n---\n# Welcome\n\nHello world.\n",
                           "about.md": "---\ntitle: About\n---\n# About Us\n\nWe are cool.\n",
                           "blog/post1.md": "---\ntitle: First Post\ndate: 2025-01-15\n---\n# Post 1\n",
                       },
                       template_files=MINIMAL_TEMPLATES)
        rc, _, err = run_ssg(["build"], self.tmpdir)
        self.assertEqual(rc, 0, f"Build failed:\n{err}")
        output = self.tmpdir + "/output"
        self.assertTrue(os.path.isfile(f"{output}/index.html"))
        self.assertTrue(os.path.isfile(f"{output}/about/index.html"))
        self.assertTrue(os.path.isfile(f"{output}/blog/post1/index.html"))

    def test_rebuild_overwrites_output(self):
        """Running build twice produces same result (idempotent)."""
        create_project(self.tmpdir, config_yaml=MINIMAL_CONFIG,
                       content_files={
                           "page.md": "---\ntitle: Page\n---\nContent.\n"
                       },
                       template_files=MINIMAL_TEMPLATES)
        run_ssg(["build"], self.tmpdir)
        # Build again
        rc, _, err = run_ssg(["build"], self.tmpdir)
        self.assertEqual(rc, 0, f"Rebuild failed:\n{err}")
        self.assertTrue(os.path.isfile(
            os.path.join(self.tmpdir, "output", "page", "index.html")))

    def test_output_is_valid_html(self):
        """Output files contain valid HTML structure."""
        create_project(self.tmpdir, config_yaml=MINIMAL_CONFIG,
                       content_files={
                           "test.md": "---\ntitle: Test\n---\n# Hello\n"
                       },
                       template_files=MINIMAL_TEMPLATES)
        rc, _, err = run_ssg(["build"], self.tmpdir)
        self.assertEqual(rc, 0, f"Build failed:\n{err}")
        with open(os.path.join(self.tmpdir, "output", "test", "index.html")) as f:
            html = f.read()
        self.assertIn("<!DOCTYPE html>", html)
        self.assertIn("<html>", html)
        self.assertIn("</html>", html)
        self.assertIn("<head>", html)
        self.assertIn("<body>", html)


# ---------------------------------------------------------------------------
# Clean command
# ---------------------------------------------------------------------------

class TestClean(unittest.TestCase):
    """Tests for the clean command."""

    def setUp(self):
        self.tmpdir = tempfile.mkdtemp(prefix="ssg_test_")

    def tearDown(self):
        shutil.rmtree(self.tmpdir, ignore_errors=True)

    def test_clean_removes_output_dir(self):
        """Clean command removes the output directory."""
        create_project(self.tmpdir, config_yaml=MINIMAL_CONFIG,
                       content_files={"index.md": "---\ntitle: Home\n---\n# Hi\n"},
                       template_files=MINIMAL_TEMPLATES)
        run_ssg(["build"], self.tmpdir)
        output_dir = os.path.join(self.tmpdir, "output")
        self.assertTrue(os.path.isdir(output_dir))
        rc, _, err = run_ssg(["clean"], self.tmpdir)
        self.assertEqual(rc, 0, f"Clean failed:\n{err}")
        self.assertFalse(os.path.isdir(output_dir))

    def test_clean_when_no_output_dir(self):
        """Clean succeeds even if output directory doesn't exist."""
        create_project(self.tmpdir, config_yaml=MINIMAL_CONFIG,
                       content_files={},
                       template_files=MINIMAL_TEMPLATES)
        rc, _, err = run_ssg(["clean"], self.tmpdir)
        self.assertEqual(rc, 0, f"Clean should succeed when no output dir:\n{err}")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

class TestCLI(unittest.TestCase):
    """Tests for command-line interface."""

    def setUp(self):
        self.tmpdir = tempfile.mkdtemp(prefix="ssg_test_")

    def tearDown(self):
        shutil.rmtree(self.tmpdir, ignore_errors=True)

    def test_help_flag(self):
        """--help flag shows usage information."""
        rc, out, err = run_ssg(["--help"], self.tmpdir)
        self.assertEqual(rc, 0)
        combined = out + err
        self.assertIn("build", combined.lower())

    def test_build_subcommand_help(self):
        """build --help shows build-specific options."""
        rc, out, err = run_ssg(["build", "--help"], self.tmpdir)
        self.assertEqual(rc, 0)

    def test_no_args_shows_help_or_error(self):
        """Running with no args shows help or a usage hint."""
        rc, out, err = run_ssg([], self.tmpdir)
        combined = out + err
        # Should show some usage info or return non-zero
        if rc != 0:
            self.assertNotIn("Traceback", combined)

    def test_custom_config_path(self):
        """Build with -c flag uses alternate config file."""
        alt_config = "title: Alt Config\noutput_dir: alt_output\n"
        with open(os.path.join(self.tmpdir, "alt.yaml"), "w") as f:
            f.write(alt_config)
        create_project(self.tmpdir, config_yaml=None,
                       content_files={"index.md": "---\ntitle: Home\n---\n# Home\n"},
                       template_files=MINIMAL_TEMPLATES)
        rc, _, err = run_ssg(["build", "-c", "alt.yaml"], self.tmpdir)
        self.assertEqual(rc, 0, f"Build with alt config failed:\n{err}")
        self.assertTrue(os.path.isdir(os.path.join(self.tmpdir, "alt_output")))

    def test_build_exit_code_zero_on_success(self):
        """Successful build returns exit code 0."""
        create_project(self.tmpdir, config_yaml=MINIMAL_CONFIG,
                       content_files={"index.md": "---\ntitle: Home\n---\n# Home\n"},
                       template_files=MINIMAL_TEMPLATES)
        rc, _, _ = run_ssg(["build"], self.tmpdir)
        self.assertEqual(rc, 0)


# ---------------------------------------------------------------------------
# Error handling
# ---------------------------------------------------------------------------

class TestErrorHandling(unittest.TestCase):
    """Tests for error handling and edge cases."""

    def setUp(self):
        self.tmpdir = tempfile.mkdtemp(prefix="ssg_test_")

    def tearDown(self):
        shutil.rmtree(self.tmpdir, ignore_errors=True)

    def test_missing_content_dir_handled(self):
        """Build handles missing content directory gracefully."""
        config = "title: Test\ncontent_dir: nonexistent\n"
        create_project(self.tmpdir, config_yaml=config,
                       content_files=None,
                       template_files=MINIMAL_TEMPLATES)
        # Remove content dir if it was created
        content_dir = os.path.join(self.tmpdir, "content")
        if os.path.isdir(content_dir):
            shutil.rmtree(content_dir)
        rc, out, err = run_ssg(["build"], self.tmpdir)
        combined = out + err
        self.assertNotIn("Traceback", combined)

    def test_missing_template_dir_produces_error(self):
        """Build fails cleanly when template directory is missing."""
        config = "title: Test\ntemplate_dir: nonexistent_templates\n"
        create_project(self.tmpdir, config_yaml=config,
                       content_files={"index.md": "---\ntitle: Home\n---\n# Home\n"},
                       template_files=None)
        # Remove template dir
        tmpl_dir = os.path.join(self.tmpdir, "templates")
        if os.path.isdir(tmpl_dir):
            shutil.rmtree(tmpl_dir)
        rc, out, err = run_ssg(["build"], self.tmpdir)
        combined = out + err
        self.assertNotIn("Traceback", combined)

    def test_no_traceback_on_user_errors(self):
        """User-facing errors never show Python tracebacks."""
        # Build with no content dir, no templates, no config
        rc, out, err = run_ssg(["build"], self.tmpdir)
        combined = out + err
        self.assertNotIn("Traceback", combined)


if __name__ == "__main__":
    unittest.main()
'''


if __name__ == "__main__":
    main()
